name: Flutter CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.5'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Preparar .env para tests
      run: |
        cp .env.development.example .env
        echo "WEBHOOK_URL=https://dummy.url" >> .env
    
    - name: Format code
      run: dart format .
    
    - name: Analyze project source
      run: flutter analyze
      continue-on-error: true
    
    - name: Run tests
      run: flutter test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Build APK Release
        run: flutter build apk --release
        continue-on-error: true
      - name: Upload APK Release
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
        continue-on-error: true 